### Créer un nouvel utilisateur (valide)

POST http://localhost:3000/api/users/connexion
Content-Type: application/json

{
  "username": "APIPIII4",
  "password": "MotDePasseSecurise123"
}

### Tester l'API 

POST http://localhost:3000/api/abonnements/nouvelAbonnement
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMzMywiaWF0IjoxNzQ3NjgxNjg0LCJleHAiOjE3NDc2ODUyODR9.qarG8a4tsFvHYo8C_Uy2t886pICdPUYxJUMu3YAqGh8

{
  "userId": 333,
  "name": "Test",
  "price": 10,
  "date": 10
}

### CONNEXION 